# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54cbedafa21d1be55b025f5cc35b24c36d571ae78647acf61149b9004cf99c8414fb2ef50094f40b9cb9f7dc81e214b80a6cf42b37e3ee3f4425148e60ee4fb9

test:
  secret_key_base: ce9d2a29ef07bcd6a5961cfcf1c2b646490fff8adbfd1e77eb944123be5fd9c1c4c486209c725f59c2c10f606ebc5bc33dce798745b3f390873956ff13724917

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
